Controllers/SignInController.cs
using Best_UI_React_App.Azure_Services;
using Best_UI_React_App.DB_Services;
using Best_UI_React_App.ExtensionMethods;
using Best_UI_React_App.Mail_Services;
using Best_UI_React_App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Tasks;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using NuGet.Common;
using NuGet.Protocol.Plugins;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;

namespace Best_UI_React_App.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class SignInController : Controller
    {
        private readonly ILogger<SignInController> _logger;// In Future set the logging to application Insights
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly UserDBContext _context;
        private AzureImageResponse signedUrlForImageResponse;
        private IAzureUploadServices _uploadServices;
        private readonly IMailService _mailService;
        private IDBUser_Services _dbServices;

        public SignInController(ILogger<SignInController> logger, SignInManager<User> signInManager, UserManager<User> userManager, UserDBContext context, IAzureUploadServices uploadServices, IDBUser_Services dbServices, IMailService mailService)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
            signedUrlForImageResponse = new AzureImageResponse();
            _uploadServices = uploadServices;
            _dbServices = dbServices;
            _mailService = mailService;
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromBody] Login login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _signInManager.PasswordSignInAsync(login.Username, login.Password, login.RememberMe, false);
                    var username = await _userManager.FindByNameAsync(login.Username);
                    if (username != null)
                    {                        
                        var activeUserId = await _userManager.GetUserIdAsync(username);
                        var details = _context.AppUsers
                                        .Where(u => u.Id == activeUserId)
                                        .Select(x => new { x.IsUserActive, x.EmailConfirmed, x.PasswordHash, x.Email }).SingleOrDefault();

                        if (result.Succeeded && details.IsUserActive && details.EmailConfirmed)
                        {
                            List<string> error = new List<string>();
                            string uniqueFileName = string.Empty;
                            var userDetails = _dbServices.CallingUserDetails(details.Email);
                            uniqueFileName = userDetails.Item1.FileName;

                            string imgSrcResult = _dbServices.CallingUserImgSrc(userDetails.Item1);

                            string encryptedId = userDetails.Item2.ToString().EncryptNumber();

                            if (result.Succeeded && !String.IsNullOrEmpty(imgSrcResult))
                            {
                                return new JsonResult(new { login_successful = true, Username = login.Username, Id = encryptedId, userDetails = userDetails.Item1, imageSrc = imgSrcResult });
                            }
                            else if (result.Succeeded)
                            {
                                return new JsonResult(new { login_successful = true, Username = login.Username, Id = encryptedId, userDetails = userDetails.Item1, imageSrc = "" });
                            }
                        }
                        else if (String.IsNullOrEmpty(details.PasswordHash))
                        {
                            return new JsonResult(new { login_successful = false, Username = login.Username, error = "Please Sign in with Google or click on Sign Up link to activate your account." });
                        }
                        else if (details.EmailConfirmed == false)
                        {
                            return new JsonResult(new { login_successful = false, Username = login.Username, error = "User email not activated. Please activate your account by clicking on the link sent to your registered email address." });
                        }
                        else if (details.IsUserActive == false)
                        {
                            return new JsonResult(new { login_successful = false, Username = login.Username, error = "User got deleted. Please register again." });
                        }
                        else
                        {
                            return new JsonResult(new { login_successful = false, Username = login.Username, error = "Login Failed. Please try again with valid credentials" });
                        }
                    }
                    else
                    {
                        return new JsonResult(new { login_successful = false, error = $"User is not found. {login.Username.ToUpper()} please register yourself." });
                    }
                }
            }
            catch (Exception ex)
            {
                return new JsonResult(new { login_successful = false, error = $"Internal server error: {ex.Message}" });
            }

            return new JsonResult(new { login_successful = false, error = "Login Failed" });
        }

        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string userId, string token)
        {
            if (userId == null || token == null)
            {
                ViewBag.ErrorMessage = $"The User ID is invalid";
                return View("Error");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"The User ID {userId} is invalid";
                return View("Error");
            }

            string decodedToken = HttpUtility.UrlDecode(token);
            var result = await _userManager.ConfirmEmailAsync(user, decodedToken);
            if (result.Succeeded)
            {
                return View();
            }

            ViewBag.ErrorMessage = "Email cannot be confirmed";
            return View("Error");
        }        

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ResetPassword(string email, string token)
        {
            if (email == null || token == null)
            {
                ViewBag.ErrorMessage = $"The email is invalid";
                return View("ResetPasswordErrorPage");
            }

            var model = new ForgotPassword { Token = token, Email = email };
            return View(model);            
        }

        [HttpPost]        
        public async Task<IActionResult> ResetPassword(ForgotPassword forgotPasswordModel)
        {
            if (!ModelState.IsValid)
                return View(forgotPasswordModel);
            var user = await _userManager.FindByEmailAsync(forgotPasswordModel.Email);
            if (user == null)
                RedirectToAction(nameof(ResetPasswordSuccessful));
            string decodedToken = HttpUtility.UrlDecode(forgotPasswordModel.Token);
            var resetPassResult = await _userManager.ResetPasswordAsync(user, decodedToken, forgotPasswordModel.NewPassword);
            List<string> errors = new List<string>();
            if (!resetPassResult.Succeeded)
            {
                foreach (var error in resetPassResult.Errors)
                {
                    ModelState.TryAddModelError(error.Code, error.Description);
                    errors.Add(error.Description);
                }
                return new JsonResult(new { forgotPasswordModel, errors });                
            }
            return new JsonResult(new { status = "success", email = forgotPasswordModel.Email });            
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ResetPasswordSuccessful(string email)
        {
            if (email == null)
            {
                ViewBag.ErrorMessage = $"The email is invalid";
                return View("ResetPasswordErrorPage");
            }

            ViewBag.Email = email;
            
            return View();
        }      

        [HttpPost]
        public async Task<IActionResult> ExternalLogin([FromBody] Object userObj)
        {
            try
            {
                if (userObj != null)
                {
                    var data = JsonConvert.DeserializeObject<dynamic>(userObj.ToString());
                    string email = data.email;
                    string name = data.displayName;                      
                    string providerKey = data.providerData[0].uid;
                    string loginProvider = data.providerData[0].providerId;

                    //If the user already has a login(i.e if there is a record in AspNetUserLogins
                    // table) then sign-in the user with this external login provider
                    var signInResult = await _signInManager.ExternalLoginSignInAsync(loginProvider,
                        providerKey, isPersistent: false, bypassTwoFactor: true);

                    if (signInResult.Succeeded)
                    {
                        var externalUserGUID = _context.ExternalUserLogins
                                        .Where(u => u.ProviderKey == providerKey)
                                        .Select(x => new User

Views/SignIn/ConfirmEmail.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>User email verified</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#dialog").dialog();
        });
    </script>
</head>
<body>

    <div id="dialog" title="User email verified">
        <h3>
            Thank you for confirming your email. Now you have access to the rrr-stocks website. Please click here -
            <a href="https://rrr-stocks.com/login"
               target="_blank"
               class="link2"
               style="
                                      color: #475c77;
                                      text-decoration: none;
                                    ">
                <span class="link2"
                      style="
                                        color: #475c77;
                                        text-decoration: none;
                                        font-weight: bold;
                                      ">Login page</span>
            </a>
        </h3>
    </div>    

</body>
</html>

Views/SignIn/ResetPassword.cshtml
@model Best_UI_React_App.Models.ForgotPassword;

<!-- Bootstrap CDN -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script data-require="jquery" data-semver="2.2.0" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css" />

<h2>Reset Password</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="ResetPassword">
            <div class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">New Password: </label>
                <input class="form-control" id="NewPassword" />                
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Confirm Password: </label>
                <input class="form-control" id="ConfirmPassword" />                
            </div>
            <br />
            <div class="form-group">
                <button type="button" value="Submit" id="submit" class="btn btn-primary">Submit</button>
            </div>
            <br>
            <div id="showloding" style="display:none">
                <div class="spinner-grow spinner-grow-sm" role="status">
                </div>
                <div class="spinner-grow spinner-grow-sm" role="status">
                </div>
                <div class="spinner-grow spinner-grow-sm" role="status">
                </div>
            </div>
            <br />
            <div id="dvMessage" visible="false" class="alert alert-danger" style="display:none">
                <strong>Error!</strong>
                <label id="lblMessage" />
            </div>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        //$("button#submit").prop('disabled', false);        
        $("button#submit").show();
        $('#showloding').hide();
        $('#dvMessage').hide();
    });

    $("button#submit").click(function () {        
        $('#dvMessage').hide();
        $("button#submit").hide();
        //$("button#submit").prop('disabled', true);
        $('#showloding').show();
        var ConfirmPassword = $("#ConfirmPassword").val();
        var NewPassword = $("#NewPassword").val();

        var userdata = JSON.stringify({
            'Email': @Html.Raw(Json.Serialize(Model.Email)),
            'ConfirmPassword': ConfirmPassword,
            'Token': @Html.Raw(Json.Serialize(Model.Token)),
            'NewPassword': NewPassword
        });

        $.ajax({
            type: 'POST',
            dataType: 'json',
            url: '@Url.Action("ResetPassword", "SignIn")',
            data: userdata,
            contentType: "application/json; charset=utf-8",
            async: false,
            success: function (result) {
                //$("button#submit").prop('disabled', false);
                $("button#submit").show();
                $('#showloding').hide();
                if (result.status == 'success') {
                    var email1 = result.email
                    window.location = '@Url.Action("ResetPasswordSuccessful","SignIn", new { email = Model.Email })';
                }
                else {
                    var errors = result.errors;
                    $('#dvMessage').show();
                    $.each(errors, function (index, value) {
                        $("#lblMessage").text(value);
                    });
                }

            },

            error: function (jqXHR, exception) {
                var msg = '';
                //$("button#submit").prop('disabled', false);
                $("button#submit").show();
                $('#showloding').hide();
                if (jqXHR.status === 0) {
                    msg = 'Not connect.\n Verify Network.';
                    alert(msg);
                } else if (jqXHR.status == 404) {
                    msg = 'Requested page not found. [404]';
                    alert(msg);
                } else if (jqXHR.status == 500) {
                    msg = 'Internal Server Error [500].';
                    $('#errordate').show();
                    if ($("#state").val() == "") {
                        $('#errorstate').show();
                    }
                    //$("button#submit").prop('disabled', false);
                    $("button#submit").show();
                    $('#showloding').hide();
                } else if (exception === 'parsererror') {
                    msg = 'Requested JSON parse failed.';
                    alert(msg);
                } else if (exception === 'timeout') {
                    msg = 'Time out error.';
                    alert(msg);
                } else if (exception === 'abort') {
                    msg = 'Ajax request aborted.';
                    alert(msg);
                } else {
                    var responseText = jQuery.parseJSON(jqXHR.responseText);
                    $('#dvMessage').show();
                    $.each(responseText.errors, function (index, value) {
                        $("#lblMessage").text(value);
                    });
                }
            }
        });
    });

</script>

Views/SignIn/ResetPasswordErrorPage.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reset password error page</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#dialog").dialog();
        });
    </script>
</head>
<body>

    <div id="dialog" title="Reset password failed">
        <h3>
            Error while resetting the password - @ViewBag.ErrorMessage
            <br />
            <br />
            <a href="https://rrr-stocks.com/login"
               target="_blank"
               class="link2"
               style="
                                      color: #475c77;
                                      text-decoration: none;
                                    ">
                <span class="link2"
                      style="
                                        color: #475c77;
                                        text-decoration: none;
                                        font-weight: bold;
                                      ">Login page</span>
            </a>
        </h3>
    </div>

</body>
</html>

Views/SignIn/ResetPasswordSuccessful.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reset Password Successful</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#dialog").dialog();
        });
    </script>
</head>
<body>

    <div id="dialog" title="Reset Password Successful">
        <h3>
            Resetting the password was successful from registered email address - @ViewBag.Email
            <br/>
            Please click here -
            <a href="https://rrr-stocks.com/login"
               target="_blank"
               class="link2"
               style="
                                      color: #475c77;
                                      text-decoration: none;
                                    ">
                <span class="link2"
                      style="
                                        color: #475c77;
                                        text-decoration: none;
                                        font-weight: bold;
                                      ">Login page</span>
            </a>
        </h3>
    </div>    

</body>
</html>